apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-prometheus-monitor
  labels:
    app: prometheus-service-monitor
spec:
  endpoints:
  - interval: 1s
    port: http
  selector:
    matchLabels:
      app: nginx-exporter

