apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework # имя CRD должно иметь формат plural.group
spec:
  group: otus.homework # Группа, отражается в поле apiVersion CR
  names: # различные форматы имени объекта CR
    kind: MySQL # kind CR
    plural: mysqls
    singular: mysql
    shortNames:
      - ms
  scope: Namespaced # Данный CRD будер работать в рамках namespace
  versions: # Список версий
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              image:
                type: string
              database:
                type: string
              password:
                type: string
              storage_size:
                type: string
            required:
              - image
              - database
              - password
              - storage_size
            type: object 
        type: object 
    served: true # Будет ли обслуживаться API-сервером данная версия
    storage: true # Версия описания, которая будет сохраняться в etcd          

